[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/time"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.14.0"

[prune]
  go-tests = true
  unused-packages = true
